### PR TITLE
Add v7.0.0 changelog

### PR DESCRIPTION
**Pull request by ShockwaveNN**

### CODE REVIEW

**Comment by chinaguole** [comment]
expect that
2221200A

**Comment by Ezekiel314** [comment]
Hello @ShockwaveNN ,
do you have an estimation date on the v7 release ?
Regards

**Comment by ShockwaveNN** [comment]
@Ezekiel314 Really hope to release it next week

**Comment by cpot** [comment]
> @Ezekiel314 Really hope to release it next week

we were really expecting the release for this week to finalize our test my GoFAST v4 so we will wait

**Comment by Ezekiel314** [comment]
It's fine, tests are important.
Thanks for the quick answers and keep the good work.

**Comment by ShockwaveNN** [comment]
@Ezekiel314 Thanks for understanding. With vast new features in v7.0 and the usual big list of supported platforms, it's not a `week` task to check that everything works as it should

**Pull request merged**
